version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.4.0
    container_name: localstack
    environment:
      - DEBUG=0
      - PROVIDER_OVERRIDE_LAMBDA=asf
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: quantum-network
    driver: bridge