version: "3.8"

services:
  customer-api:
    image: quantum-customer-api:1.0.1
    container_name: customer-api
    environment:
      - DynamoDb__Region=localstack
      - DynamoDb__LocalstackUri=http://localstack:4566
      - Logging__LogLevel__Microsoft.AspNetCore=Information
    ports:
      - 9001:80
    depends_on:
      - localstack
    profiles:
      - customer-api
      - all
 
  account-api:
    image: quantum-account-api:1.0.1
    container_name: account-api
    environment:
      - DynamoDb__Region=localstack
      - DynamoDb__LocalstackUri=http://localstack:4566
    ports:
      - 9002:80
    depends_on:
      - localstack
    profiles:
      - account-api
      - all
 
  account-search-api:
    image: quantum-account-search-api:1.0.1
    container_name: account-search-api
    environment:
      - AccountSearchDb__ConnectionString=Server=postgres;Port=5432;Userid=postgres;Password=postgres;Database=AccountSearch
    ports:
      - 9003:80
    depends_on:
      account-search-api-migrator:
        condition: service_completed_successfully
    profiles:
      - account-search-api
      - all

  account-search-api-migrator:
    image: quantum-account-search-api:1.0.1
    container_name: account-search-api-migrator
    command: "--migrate=true"
    environment:
      - AccountSearchDb__ConnectionString=Server=postgres;Port=5432;Userid=postgres;Password=postgres;Database=AccountSearch
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - account-search-api
      - all

  account-customer-consumer:
    image: quantum-account-customer-consumer:1.0.1
    container_name: account-customer-consumer
    environment:
      - DynamoDb__Region=localstack
      - DynamoDb__LocalstackUri=http://localstack:4566
      - Kafka__BootstrapServers=kafka:9094
    depends_on:
      localstack:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
    profiles:
      - account-customer-consumer
      - all

  account-search-projection:
    image: quantum-account-search-projection:1.0.1
    container_name: account-search-projection
    environment:
      - AccountSearchDb__ConnectionString=Server=postgres;Port=5432;Userid=postgres;Password=postgres;Database=AccountSearch
      - Kafka__BootstrapServers=kafka:9094
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
    profiles:
      - account-search-projection
      - all

  manager-gateway:
    image: traefik:v2.9
    container_name: manager-gateway
    environment:
      - TRAEFIK_PROVIDERS_FILE=true
      - TRAEFIK_PROVIDERS_FILE_DIRECTORY=/etc/traefik/
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_LOG_LEVEL=INFO
    ports:
      - 9012:80
      - 9022:8080
    volumes:
      - ./manager-gateway.yaml:/etc/traefik/manager-gateway.yaml
    profiles:
      - all
      - manager-gateway
